In [67]:
#
# ETL Project Group 6 Team Bamboo
#   Dan C.
#

import pandas as pd
file = 'Resources/location-identifier-database-202103.csv'
icao_df = pd.read_csv(file, encoding="ISO-8859-1",low_memory=False)

usa_icao_df = icao_df.loc[icao_df['country3'] == "USA"] # Select just US stationis
new_icao_df = usa_icao_df.reset_index(drop=True)
new_icao_df.dropna(subset = ["icao"], inplace=True)

new_icao_df.reset_index(drop=True)
clean_icao_df = new_icao_df.drop(['country2','country','stn_key', 'status','national_id', 'wmo','wban','ghcn','special'],1)
clean_icao_df.reset_index(drop=True, inplace=True)

clean_icao_df = clean_icao_df.drop_duplicates(subset=['icao'],keep='last')

df_out_file = 'Resources/icao.csv'
clean_icao_df.to_csv(df_out_file, index = True, header=True)
print (clean_icao_df)

     country3 region subregion  \
0         USA      -         -
1         USA      -         -
2         USA      -         -
3         USA      -         -
4         USA      -         -
...       ...    ...       ...
6010      USA    NaN       NaN
6011      USA    NaN       NaN
6012      USA    NaN       NaN
6013      USA    NaN       NaN
6014      USA    NaN       NaN

                                            place_name  \
0                                                 Buoy
1                                  Buoy - Moored Centr
2                                        Pacific Ocean
3                                        Pacific Ocean
4                                          Wake Island
...                                                ...
6010     Hickam Usaf Automatic Weather Switch,oahu,hi.
6011                         Kunia Forecast Center,hi.
6012                           Nome (met Radar Sitejak
6013  Oahu (usaf Solar Faare Forecast I Facility) .hi.
6014                Usn (facsfac Hawaii), Honolulu,hi.

                                          station_name  \
0                                                Hotel
1                                  Buoy - Moored Centr
2                                             Ship 4YP
3                                             Ship 4YT
4                                       Wake Island AP
...                                                ...
6010     Hickam Usaf Automatic Weather Switch,oahu,hi.
6011                         Kunia Forecast Center,hi.
6012                           Nome (met Radar Sitejak
6013  Oahu (usaf Solar Faare Forecast I Facility) .hi.
6014                Usn (facsfac Hawaii), Honolulu,hi.

                                                  notes type  icao       lat  \
0                                                   NaN  NaN  KC7H  38.50000
1                                                   NaN  NaN  KQ51  26.01700
2     This station was active mainly in the 1970s an...  NaN  K4YP  50.00000
3     This station was active mainly in the 1970s an...  NaN  K4YT  29.00000
4                                                   NaN  NaN  PAWK  19.28249
...                                                 ...  ...   ...       ...
6010                                                NaN  NaN  PHWR       NaN
6011                                                NaN  NaN  PHKU       NaN
6012                                                NaN  NaN  PAME       NaN
6013                                                NaN  NaN  PHFF       NaN
6014                                                NaN  NaN  PHNF       NaN

             lon  elev
0     -70.700000   NaN
1     -87.750000   NaN
2    -145.000000   NaN
3     135.000000   NaN
4     166.636661   7.0
...          ...   ...
6010         NaN   NaN
6011         NaN   NaN
6012         NaN   NaN
6013         NaN   NaN
6014         NaN   NaN

[5896 rows x 11 columns]

In [49]:
clean_icao_df.dtypes

country3         object
country          object
region           object
subregion        object
place_name       object
station_name     object
notes            object
type             object
icao             object
lat             float64
lon             float64
elev            float64
dtype: object

In [61]:
clean_icao_df.head(200)

,country3,region,subregion,place_name,station_name,notes,type,icao,lat,lon,elev
0,USA,-,-,Buoy,Hotel,NaN,NaN,KC7H,38.500000,-70.700000,NaN
1,USA,-,-,Buoy - Moored Centr,Buoy - Moored Centr,NaN,NaN,KQ51,26.017000,-87.750000,NaN
2,USA,-,-,Pacific Ocean,Ship 4YP,This station was active mainly in the 1970s an...,NaN,K4YP,50.000000,-145.000000,NaN
3,USA,-,-,Pacific Ocean,Ship 4YT,This station was active mainly in the 1970s an...,NaN,K4YT,29.000000,135.000000,NaN
4,USA,-,-,Wake Island,Wake Island AP,NaN,NaN,PAWK,19.282490,166.636661,7.0
...,...,...,...,...,...,...,...,...,...,...,...
195,USA,AK,Ketchikan Gateway Borough,Ketchikan|Peninsula Point,Murphys Pullout,NaN,NaN,K8K9,55.389650,-131.738074,0.0
196,USA,AK,Ketchikan Gateway Borough,Ketchikan|Peninsula Point,Peninsula Point Pullout,NaN,NaN,K9C0,55.384651,-131.738352,0.0
197,USA,AK,Northwest Arctic Borough,Kiana,Bob Baker Memorial,NaN,NaN,PAIK,66.975953,-160.436533,55.2
198,USA,AK,Aleutians East Borough,King Cove,King Cove,NaN,NaN,PAVC,55.116347,-162.266247,45.1
199,USA,AK,Bristol Bay Borough,King Salmon,King Salmon AFS,NaN,NaN,KQRC,58.683000,-156.667000,7.0